[features]
resolution = true
skip-lint = false

[programs.localnet]
cpi_swap_program = "8KQG1MYXru73rqobftpFjD3hBD8Ab3jaag8wbjZG63sx"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/cpi-swap-program.ts"
deploy-local = "solana program deploy target/deploy/cpi_swap_program.so --program-id target/deploy/cpi_swap_program-keypair.json -C ~/.config/solana/cli/local.yml --use-rpc --with-compute-unit-price 10"
deploy-mainnet = "solana program deploy target/deploy/cpi_swap_program.so --program-id target/deploy/cpi_swap_program-keypair.json -C ~/.config/solana/cli/config.yml --use-rpc --with-compute-unit-price 10"


# anchor idl init -f ./target/idl/cpi_swap_program.json 8KQG1MYXru73rqobftpFjD3hBD8Ab3jaag8wbjZG63sx --provider.wallet ~/.config/solana/id.json --provider.cluster <RPC>

# anchor idl upgrade --filepath ./target/idl/cpi_swap_program.json 8KQG1MYXru73rqobftpFjD3hBD8Ab3jaag8wbjZG63sx --provider.wallet ~/.config/solana/id.json --provider.cluster  <RPC>
